DROP SCHEMA IF EXISTS DEMO;
CREATE SCHEMA DEMO;
USE DEMO;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON
(
ID int NOT NULL AUTO_INCREMENT,
LASTNAME varchar(255) NOT NULL,
FIRSTNAME varchar(255),
PRIMARY KEY (ID)
);